# Generated by Django 5.2.1 on 2025-07-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0002_remove_typeutilisateur_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nombre_commandes', models.PositiveIntegerField()),
                ('nombre_clients', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatutCommande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='adminApp.utilisateurs')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='businessApp.statutcommande')),
            ],
        ),
        migrations.CreateModel(
            name='ElementMenu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='menu/')),
                ('est_epuise', models.BooleanField(default=False)),
                ('specialite_jour', models.BooleanField(default=False)),
                ('allergenes', models.ManyToManyField(blank=True, related_name='plats', to='businessApp.allergene')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='businessApp.commande')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu/')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='businessApp.elementmenu')),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='businessApp.commande')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businessApp.elementmenu')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_place', models.PositiveIntegerField()),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('heure', models.TimeField()),
                ('statut', models.CharField(default='En attente', max_length=50)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='adminApp.utilisateurs')),
            ],
        ),
    ]
