# Generated by Django 5.2.1 on 2025-07-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementmenu',
            name='image',
        ),
    ]
