# Generated by Django 5.2.1 on 2025-07-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0002_remove_elementmenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menujour',
            name='plats',
            field=models.ManyToManyField(related_name='menus_jour', to='businessApp.elementmenu'),
        ),
    ]
