# Generated by Django 5.2.1 on 2025-07-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0003_menujour_plats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=50),
        ),
    ]
