# Generated by Django 5.2.1 on 2025-08-01 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0004_alter_reservation_date_reservation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacite', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='lignecommande',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessApp.elementmenu'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(related_name='reservations', to='businessApp.table'),
        ),
    ]
