# Generated by Django 5.2.1 on 2025-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeutilisateur',
            name='permission',
        ),
        migrations.AddField(
            model_name='typeutilisateur',
            name='permissions',
            field=models.ManyToManyField(related_name='types_utilisateurs', to='adminApp.permission'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typeutilisateur',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
