# Generated by Django 5.2.1 on 2025-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_remove_typeutilisateur_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='utilisateurs',
            name='telephone',
            field=models.CharField(null=True),
        ),
    ]
